version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "tests/requirements.txt" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            npm install --ignore-scripts
            python3 -m venv venv
            . venv/bin/activate
            pip install -r tests/requirements.txt --quiet

      - save_cache:
          paths:
            - ./venv
            - ./node_module
          key: v1-dependencies-{{ checksum "tests/requirements.txt" }}-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: build
          command: |
            . venv/bin/activate
            npm run build:all

      - run:
          name: lint
          command: |
            npm run lint
            npm run format:test

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
